micronaut:
  application:
    name: TAXII-Server-Micronaut
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /redoc/**
        http-method: GET
        access:
          - isAnonymous()

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**